default: &default
  adapter: sqlserver
  host: localhost
  port: 1433
  username: sa
  # password: ThuatDev@2002
  password: Thuat123
  database: railscoursedb
  encoding: utf8

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
